apiVersion: v1
data:
  db-password: YXdqb3JnaWpmNDM4JkFZKldEMzJneTNmR0FZV0QjJipBJiNHRiojQSZHRUZEeWVnYTh3NDdnKkEmI0dG
kind: Secret
metadata:
  namespace: server-panel
  labels:
    io.kompose.service: db-password
  name: db-password
type: Opaque
