apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: server-panel
  labels:
    io.kompose.service: mongodb
  name: mongodb-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
