apiVersion: v1
data:
  nginx.conf: |
    server {
      listen 80;
      server_name localhost;

      location / {
          proxy_pass http://frontend:3000;
          proxy_set_header Host $host;
      }

      location /api/ {
          proxy_pass http://backend:3000;
          proxy_set_header Host $host;
      }

      location /adminer {
          proxy_pass http://adminer:8080;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
      }

      location /mqtt {
          proxy_pass http://mqtt:8003;

          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection "upgrade";
          
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          
          proxy_read_timeout 86400;
          proxy_send_timeout 86400;
      }
    }
kind: ConfigMap
metadata:
  namespace: server-panel
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: nginx
  name: nginx-cm0
