
name: Node.js CI

on:
  push:
    branches: [ "main", "Auth0" ]
    paths:
      - "backend/**"
  pull_request:
    branches: [ "main", "Auth0" ]
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:latest
        ports:
          - 27017:27017
      redis:
        image: redis:alpine
        ports:
          - 6379:6379
      mqtt:
        image: eclipse-mosquitto:1.6.15
        ports:
          - 1883:1883

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v4
      
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'backend/package-lock.json'

    - name: Install dependencies
      working-directory: backend
      run: npm ci

    - name: Run tests
      env:
        REDIS_URL: redis://redis:6379
        WEB_HOST: http://nginx
        MONGODB_URI: mongodb://mongodb:27017/database
        BACKEND_PORT: 3000
      working-directory: backend
      run: npm test 